In [1]:
import pandas as pd
s = pd.Series([9904312, 3448737, 2890451, 2446052], index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2446052
dtype: int64

In [2]:
pd.Series(range(10,14))

0    10
1    11
2    12
3    13
dtype: int64

In [3]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [4]:
s.values

array([9904312, 3448737, 2890451, 2446052], dtype=int64)

In [5]:
s.name ="인구"
s.index.name= "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2446052
Name: 인구, dtype: int64

In [6]:
s/1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.446052
Name: 인구, dtype: float64

In [7]:
s[1], s["부산"]

(3448737, 3448737)

In [8]:
s[3],s["대구"]

(2446052, 2446052)

In [9]:
s[[0,3,1]]

도시
서울    9904312
대구    2446052
부산    3448737
Name: 인구, dtype: int64

In [10]:
s[["서울", "대구", "부산"]]

도시
서울    9904312
대구    2446052
부산    3448737
Name: 인구, dtype: int64

In [11]:
s[(250e4 < s) & (s < 500e4)]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [12]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2446052
Name: 인구, dtype: int64

In [13]:
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [14]:
s["부산":"대구"]

도시
부산    3448737
인천    2890451
대구    2446052
Name: 인구, dtype: int64

In [15]:
s0 = pd.Series(range(3), index=["a", "b","c"])
s0

a    0
b    1
c    2
dtype: int64

In [16]:
s0.a

0

In [17]:
s0.b

1

In [18]:
"서울" in s

True

In [19]:
"대전" in s

False

In [20]:
for k, v in s.items():
    print("{} = {}".format(k,v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2446052


In [21]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158 })
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [22]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158 }, 
               index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [23]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [24]:
s.values

array([9904312, 3448737, 2890451, 2446052], dtype=int64)

In [25]:
s2.values

array([3393191, 9631482, 2632035, 1490158], dtype=int64)

In [26]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   955894], dtype=int64)

In [27]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [28]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [29]:
rs = (s-s2)/s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

In [30]:
rs["부산"]=1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [31]:
rs["대구"]=1.41
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [32]:
del rs["서울"]
rs

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64

In [33]:
# 데이터프레임 클래스

In [34]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [35]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [36]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [37]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [38]:
# 시리즈처럼 열방향 인덱스와 행방향 인덱스에 이름을 붙이는 것도 가능하다.
df.index.name = "도시"
df.columns.name ="특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [39]:
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [40]:
# 데이타프레임 열 인덱싱
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [41]:
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [42]:
df[["2010"]]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [43]:
# column based slicing
df.loc[:, "2010":"2005"]

특성     2010     2005
도시                  
서울  9631482  9762546
부산  3393191  3512547
인천  2632035  2517680
대구  2431774  2456016

In [44]:
type(df[["2010"]])

pandas.core.frame.DataFrame

In [45]:
df["2010"]

도시
서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [46]:
type(df["2010"])

pandas.core.series.Series

In [47]:
import numpy as np
df2 = pd.DataFrame(np.arange(12).reshape(3,4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [48]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int32

In [49]:
# 열 데이터의 갱신, 추가, 삭제 : DataFraem
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [50]:
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [51]:
df["2005-2010 증가율"] = ( (df["2010"]-df["2005"])/df["2005"]*100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시                                                                       
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [52]:
del df["2010-2015 증가율"]
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [53]:
# 개별 데이터 인덱싱
df["2015"]["서울"]

9904312

In [54]:
# 행단위 인덱싱
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [55]:
df[1:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           -3.4

In [56]:
df[1:3]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [57]:
df["부산":"인천"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [58]:
# 연습문제 3
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [59]:
df["수학"]

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [60]:
df[["국어", "영어"]]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [61]:
df["평균"] = df.T.mean().round(2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [62]:
df["평균"] = df.mean(axis=1).round(2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [63]:
df.loc["방자","영어"] = 70
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  70  70  46.67

In [64]:
df["평균"] = df.mean(axis=1).round(2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  70  70  54.17

In [65]:
df[0:1]

국어  영어  수학     평균
춘향  80  90  90  86.67

In [66]:
df.T["향단"]

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

In [67]:
# 2. 데이터 입출력

In [68]:
%%writefile sample1.csv
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Overwriting sample1.csv


In [69]:
pd.read_csv('sample1.csv')

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [70]:
%%writefile sample2.csv
1,1.11, one
2, 2.22, two
3, 3.33, three

Overwriting sample2.csv


In [71]:
pd.read_csv('sample2.csv', names=['c1', 'c2', 'c3'])

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [72]:
# 만약 테이블 내의 특정한 열을  행 인덱스로 지정하고 싶으면 index_col 인수를 사용한다.
pd.read_csv('sample1.csv', index_col='c1')

c2      c3
c1              
1   1.11     one
2   2.22     two
3   3.33   three

In [73]:
%%writefile sample3.txt
c1        c2        c3        c4 
0.179181 -1.538472  1.347553  0.43381
1.024209  0.087307 -1.281997  0.49265
0.417899 -2.002308  0.255245 -1.10515

Overwriting sample3.txt


In [74]:
pd.read_table('sample3.txt', sep='\s+')

c1        c2        c3       c4
0  0.179181 -1.538472  1.347553  0.43381
1  1.024209  0.087307 -1.281997  0.49265
2  0.417899 -2.002308  0.255245 -1.10515

In [75]:
%%writefile sample4.txt
파일 제목: sample4.txt
데이터 포맷의 설명: 
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Overwriting sample4.txt


In [76]:
pd.read_csv('sample4.txt', skiprows=[0,1])

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [77]:
%%writefile sample5.csv
c1, c2, c3
1, 1.11, one
2,, two
누락, 3.33, three

Overwriting sample5.csv


In [78]:
df = pd.read_csv('sample5.csv', na_values=['누락'])
df

c1    c2      c3
0  1.0  1.11     one
1  2.0   NaN     two
2  NaN  3.33   three

In [79]:
# CSV 파일 입출력

In [80]:
df.to_csv('sample6.csv')

In [81]:
!type sample6.csv

,c1, c2, c3
0,1.0,1.11, one
1,2.0,, two
2,,3.33, three


In [82]:
df.to_csv('sample7.txt',sep='|')

In [83]:
!type sample7.txt

|c1| c2| c3
0|1.0|1.11| one
1|2.0|| two
2||3.33| three


In [84]:
df.to_csv('sample8.csv', na_rep='누락',encoding='euc-kr')

In [85]:
!type sample8.csv

,c1, c2, c3
0,1.0,1.11, one
1,2.0,누락, two
2,누락,3.33, three


In [86]:
df.index = ['a', 'b', 'c']
df

c1    c2      c3
a  1.0  1.11     one
b  2.0   NaN     two
c  NaN  3.33   three

In [87]:
df.to_csv('sample9.csv', index=False, header=False)

In [88]:
!type sample9.csv

1.0,1.11, one
2.0,, two
,3.33, three


In [89]:
# 인터넷 상의 CSV파일 입력

In [90]:
df = pd.read_csv('https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/Titanic.csv')
df

Unnamed: 0 Class     Sex    Age Survived  Freq
0            1   1st    Male  Child       No     0
1            2   2nd    Male  Child       No     0
2            3   3rd    Male  Child       No    35
3            4  Crew    Male  Child       No     0
4            5   1st  Female  Child       No     0
5            6   2nd  Female  Child       No     0
6            7   3rd  Female  Child       No    17
7            8  Crew  Female  Child       No     0
8            9   1st    Male  Adult       No   118
9           10   2nd    Male  Adult       No   154
10          11   3rd    Male  Adult       No   387
11          12  Crew    Male  Adult       No   670
12          13   1st  Female  Adult       No     4
13          14   2nd  Female  Adult       No    13
14          15   3rd  Female  Adult       No    89
15          16  Crew  Female  Adult       No     3
16          17   1st    Male  Child      Yes     5
17          18   2nd    Male  Child      Yes    11
18          19   3rd    Male  Child      Yes    13
19          20  Crew    Male  Child      Yes     0
20          21   1st  Female  Child      Yes     1
21          22   2nd  Female  Child      Yes    13
22          23   3rd  Female  Child      Yes    14
23          24  Crew  Female  Child      Yes     0
24          25   1st    Male  Adult      Yes    57
25          26   2nd    Male  Adult      Yes    14
26          27   3rd    Male  Adult      Yes    75
27          28  Crew    Male  Adult      Yes   192
28          29   1st  Female  Adult      Yes   140
29          30   2nd  Female  Adult      Yes    80
30          31   3rd  Female  Adult      Yes    76
31          32  Crew  Female  Adult      Yes    20

In [91]:
df.head()

Unnamed: 0 Class     Sex    Age Survived  Freq
0           1   1st    Male  Child       No     0
1           2   2nd    Male  Child       No     0
2           3   3rd    Male  Child       No    35
3           4  Crew    Male  Child       No     0
4           5   1st  Female  Child       No     0

In [92]:
df.tail(2)

Unnamed: 0 Class     Sex    Age Survived  Freq
30          31   3rd  Female  Adult      Yes    76
31          32  Crew  Female  Adult      Yes    20

In [93]:
# 3. 데이터프레임 인텍서

In [94]:
df = pd.DataFrame(np.arange(10, 22).reshape(3,4), index=['a', 'b', 'c'],
                 columns=['A', 'B', 'C','D'])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [95]:
df.loc['a',"A"]

10

In [96]:
# 라벨 값의 슬라이싱 또는 리스트를 사용할 수도 있다.
df.loc["b":,"A"]

b    14
c    18
Name: A, dtype: int32

In [97]:
df.loc[["a","b"], ["B","D"]]

B   D
a  11  13
b  15  17

In [98]:
df.A

a    10
b    14
c    18
Name: A, dtype: int32

In [99]:
df.loc[df.A > 10]

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [100]:
# loc 인덱서를 사용하면 하나의 행을 시리즈 자료형으로 뽑아낼 수도 있다.
df.loc["a",:]

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [101]:
df[:1]  # loc 인덱서를 사용하지 않는 경우

A   B   C   D
a  10  11  12  13

In [102]:
def select_rows(df):
    return df.A > 12

In [103]:
select_rows(df)

a    False
b     True
c     True
Name: A, dtype: bool

In [104]:
df.loc[select_rows(df), ["B"]]

B
b  15
c  19

In [105]:
# df.loc[:,df[:1] < 11]  # 데이터프레임은 loc의 인덱서에 넣을 수 없으므로 에러!
df.loc[:,df.loc["a",:] <= 11]

A   B
a  10  11
b  14  15
c  18  19

In [106]:
# 만약 loc indexer를 사용하면서 인덱스를 하나만 넣으면 행(row)를 선택한다.
df.loc["a"]

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [107]:
df.loc["e"] = [90, 91, 92, 93]
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21
e  90  91  92  93

In [108]:
# 원래 인덱스 자체가 정수가 값을 가지는 경우에는 loc인덱서의 인덱스로 정수를 쓸 수 있다. 이때는
# 정수가 순서를 나타내는 값이 아닐 수 있다.
df2 = pd.DataFrame(np.arange(10,26).reshape(4,4), columns=np.arange(1, 8, 2))
df2

1   3   5   7
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [109]:
df2.loc[1,1]

14

In [110]:
df2.loc[1:2, :]

1   3   5   7
1  14  15  16  17
2  18  19  20  21

In [111]:
# iloc 인덱서: loc 인덱서와 반대로 라벨이 아니라 순서를 나타내는 정수(integer) 인덱스만 받는다
df.iloc[0,1]

11

In [112]:
df.iloc[:2,2]

a    12
b    16
Name: C, dtype: int64

In [113]:
df.iloc[2:3,1:3]

B   C
c  19  20

In [114]:
# loc 인덱서와 마찬가지로 인덱스가 하나만 들어가면 행을 선택한다.
df.iloc[-1]

A    90
B    91
C    92
D    93
Name: e, dtype: int64

In [115]:
df.iloc[-1] = df.iloc[-1]*2
df

A    B    C    D
a   10   11   12   13
b   14   15   16   17
c   18   19   20   21
e  180  182  184  186

In [116]:
%timeit df.loc["a","A"]

14.5 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [117]:
%timeit df.at["a", "A"]

7.94 µs ± 246 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [118]:
%timeit df.iloc[0,0]

11 µs ± 2.26 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [119]:
%timeit df.iat[0,0]

6.04 µs ± 458 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [120]:
# 4. 데이터프레임의 데이터 조작

In [121]:
s=pd.Series(range(10))
s[3]=np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [122]:
s.count()

9

In [123]:
# 데이터프레임에서는 각 열마다 별도로 데이터 갯수를 센다.
np.random.seed(2)
df = pd.DataFrame(np.random.randint(5, size=(4,4)), dtype=float)
df.iloc[2,3] = np.nan
df

0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [124]:
df.count()

0    4
1    4
2    4
3    3
dtype: int64

In [125]:
np.random.seed(1)
s2 = pd.Series(np.random.randint(6, size=100))
s2.tail()

95    4
96    5
97    2
98    4
99    3
dtype: int32

In [126]:
# value_counts 메서드로 각각의 값이 나온 횟수를 셀수 있다.
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [127]:
# 데이터프레임에는 value_counts 메서드가 없으므로 각 열마다 별도로 적용해야 한다.
df[0].value_counts()

3.0    2
4.0    1
0.0    1
Name: 0, dtype: int64

In [128]:
# 정렬
# 데이터를 정렬하려면 sort_index와 sort_values메서드를 사용한다. sort_index는 인덱스 값을 기준으로, sort_values는
# 데이터 값을 기준으로 정렬한다.
# 앞에서 s2 시리즈의 각 데이터 값에 따른 데이터 갯수를 보기 좋게 정렬하려면 다음처럼 sort_index를 적용한다.

In [129]:
s2.value_counts().sort_index()

0    18
1    22
2    13
3    14
4    17
5    16
dtype: int64

In [130]:
s.sort_values()

0    0.0
1    1.0
2    2.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
3    NaN
dtype: float64

In [131]:
# 큰 수에서 작은 수로 반대 정렬하려면 ascending=False 인수를 지정한다.
s.sort_values(ascending=False)

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
2    2.0
1    1.0
0    0.0
3    NaN
dtype: float64

In [132]:
# 데이터프레임에서 sort_values메서드를 사용하려면 by 인수로 정렬기준이 되는 열을 지정해 주어야 한다.
df.sort_values(by=1)

0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [133]:
# by 인수에 리스트 값을 넣으면 이 순서대로 정렬 기준의 우선순위가 된다. 즉. 리스트의 첫 번째 열을 기준으로 정랼한
# 후 동일한 값이 나오면 그 다음 열로 순서를 따지게 된다.
df.sort_values(by=[1,2])

0    1    2    3
1  3.0  0.0  2.0  1.0
0  0.0  0.0  3.0  2.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [134]:
## 행/열 합계

# 행과 열의 합계를 구할 때는 sum(axis) 메서드를 사용한다.
np.random.seed(1)
df2 = pd.DataFrame(np.random.randint(10, size=(4,8)))
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [135]:
# 행 합계를 구할 때는 sum(axis=1)
df2.sum(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [136]:
df2["RowSum"] = df2.sum(axis=1)
df2

0  1  2  3  4  5  6  7  RowSum
0  5  8  9  5  0  0  1  7      35
1  6  9  2  4  5  2  4  2      34
2  4  7  7  9  1  7  0  6      41
3  9  9  7  6  9  1  0  1      42

In [137]:
# 열 합계를 구할 때는 sum(axis=0) 메서드를 사용하는 데 axis 인수의  디폴트 값이 0 이므로 axis인수를 생략할 수 있다
df2.sum()

0          24
1          33
2          25
3          24
4          15
5          10
6           5
7          16
RowSum    152
dtype: int64

In [138]:
df2.loc["ColTotal",:] = df2.sum()
df2

0     1     2     3     4     5    6     7  RowSum
0          5.0   8.0   9.0   5.0   0.0   0.0  1.0   7.0    35.0
1          6.0   9.0   2.0   4.0   5.0   2.0  4.0   2.0    34.0
2          4.0   7.0   7.0   9.0   1.0   7.0  0.0   6.0    41.0
3          9.0   9.0   7.0   6.0   9.0   1.0  0.0   1.0    42.0
ColTotal  24.0  33.0  25.0  24.0  15.0  10.0  5.0  16.0   152.0

In [139]:
# apply 변환
# 행이나 열 단위로 더 복잡한 처리를 하고 싶을 때는 apply 메서드를 사용한다. 인수로 행 또는 열을 받는 함수를
# apply 메서드의 인수로 넣으면 각 열 (또는 행)을 반복하여 그 함수에 적용시킨다.

df3 = pd.DataFrame({
    "A": [1, 3, 4, 3, 4],
    "B": [2, 3, 1, 2, 3],
    "C": [1, 5, 2, 4, 4]
})
df3

A  B  C
0  1  2  1
1  3  3  5
2  4  1  2
3  3  2  4
4  4  3  4

In [140]:
# 예를 들어 각 열의 최대값과 최소값의 차이을 구하고 싶으면 다음과 같은 람다함수를 넣는다.
df3.apply(lambda x: x.max() - x.min())

A    3
B    2
C    4
dtype: int64

In [141]:
# 만약 행에 대해 적용하고 싶으면 axis=1인수를 사용한다.
df3.apply(lambda x: x.max() - x.min(), axis=1)

0    1
1    2
2    3
3    2
4    1
dtype: int64

In [142]:
# 각 열에 대혀 어떤 값이 얼마나 사용되었는지 알고 싶다면 value_counts함수를 넣을 수도 있다.
df3.apply(pd.value_counts)

A    B    C
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [143]:
# NaN값은 fillna메서드를 사용하여 원하는 값으로 변경할 수 있다. astype 메서드로 전체 데이터의 자료형을
# 바꾸는 것도 가능하다.
df3.apply(pd.value_counts).fillna(0).astype(int)

A  B  C
1  1  1  1
2  0  2  1
3  2  2  0
4  2  0  2
5  0  0  1

In [145]:
# 실수 값을 카테고리 값으로 변환
# 실수 값을 크기 기준으로 하여 카테고리 값으로 변환하고 싶을 때 다음과 같은 명령을 사용한다.
# ·cut: 실수 값의 경계선을 지정하는 경우
# ·qcut: 갯수가 똑같은 구간으로 나누는 경우
ages = [0, 2, 10, 21, 23, 37, 31, 61, 20, 41, 32, 100]

In [146]:
# cut 명령을 사용하면 실수 값을 다음처럼 카테고리 값으로 바꿀 수 있다. bins 인수는 카테고리를 나누는 기준 값이 된다
# 영역을 넘는 값은 NaN으로 처리된다.
bins = [ 1, 15, 25, 35, 60, 90]
labels = ["미성년자", "청년", "중년", "장년", "노년"]
cats = pd.cut(ages, bins, labels=labels)
cats

[NaN, 미성년자, 미성년자, 청년, 청년, ..., 노년, 청년, 장년, 중년, NaN]
Length: 12
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [147]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [148]:
cats.categories

Index(['미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [149]:
cats.codes

array([-1,  0,  0,  1,  1,  3,  2,  4,  1,  3,  2, -1], dtype=int8)

In [154]:
df4 = pd.DataFrame(ages, columns=["ages"])
df4["age_cat"] = pd.cut(df4["ages"], bins, labels=labels)
df4

ages age_cat
0      0     NaN
1      2    미성년자
2     10    미성년자
3     21      청년
4     23      청년
5     37      장년
6     31      중년
7     61      노년
8     20      청년
9     41      장년
10    32      중년
11   100     NaN

In [155]:
# qcut명령은 구간 경계선을 지정하지 않고 데이터 갯수가 같도록 저정한 수의 구간으로 나눈다. 예들들어, 다음 코드는
# 1000개의 데이터를 4개의 구간으로 나누는데 각 구간은 250개씩의 데이터를 가진다.
data = np.random.randn(1000)
cats = pd.qcut(data, 4, labels=["Q1", "Q2", "Q3", "Q4"])
cats

[Q2, Q1, Q2, Q3, Q1, ..., Q1, Q1, Q4, Q4, Q2]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [156]:
pd.value_counts(cats)

Q4    250
Q3    250
Q2    250
Q1    250
dtype: int64